services:
    ai-assistant-streamlit:
        # container_name: "streamlit-assistant"
        # build: ./src
        build:
          dockerfile: ./Dockerfile
          context: ./

        env_file:
          - .env
        
        ports:
            - 8501:8501

        command: streamlit run src/main.py --server.port 8501
        # volumes:
        #   - ./streamlit_agent/:/app/streamlit_agent

        # image: yourstreamlitapp:latest