services:
    streamlit-assistant:
        # container_name: "streamlit-assistant"
        # build: ./src
        build:
          dockerfile: ./Dockerfile
          context: ./
<<<<<<< HEAD
=======

        env_file:
          - .env
>>>>>>> c2b0f4d (Dockerizing with docker compose. And adding missing dependencies in requirements.txt)
        
        ports:
            - 8501:8501

        command: streamlit run src/main.py --server.port 8501
        # volumes:
        #   - ./streamlit_agent/:/app/streamlit_agent

        # image: yourstreamlitapp:latest