services:
    streamlit-assistant:
        # container_name: "streamlit-assistant"
        # build: ./src
        build:
          dockerfile: ./Dockerfile
          context: ./
        
        ports:
            - 8501:8501

        command: streamlit run src/main.py --server.port 8501
        # volumes:
        #   - ./streamlit_agent/:/app/streamlit_agent

        # image: yourstreamlitapp:latest